import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

// Shared static templates: edit here, then run `node scripts/build.mjs`.
// Generated HTML is committed, so Cloudflare Pages needs no build command.
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const write=(p,text)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),text+'\n');};
const imageRoot='/assets/images/';
const assets={logo:'4bf5446c40691d83.png',poster:'6b2d5e122bb88cfe.jpg',cabos:'80f5f00c7e4a7e29.jpg',xcaret:'1fde897a3226da9a.jpg',video:'/assets/video/828f446365b17e49.mp4'};
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const image=(name,alt,cls='',eager=false)=>`<img src="${imageRoot+name}" alt="${esc(alt)}" class="${cls}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const arrow='<svg class="arrow-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 20 20 4M4 4h16v16" stroke="currentColor" stroke-width="1.2"/></svg>';
const link=(href,text,cls='text-link')=>`<a class="${cls}" href="${href}">${text}${arrow}</a>`;
const kicker=(text)=>`<p class="eyebrow">${text}</p>`;
const locale=()=>`<div class="locales"><button class="locale-toggle" type="button" aria-expanded="false" aria-controls="locale-panel">PT <svg viewBox="0 0 12 8" aria-hidden="true"><path d="m1 1 5 5 5-5" fill="none" stroke="currentColor"/></svg></button><nav id="locale-panel" class="locale-panel" aria-label="Idiomas" hidden><a href="/?choose=1" lang="pt-BR" aria-current="true">Português</a><button type="button" lang="es" disabled>Español <small>Em breve</small></button><button type="button" lang="en" disabled>English <small>Em breve</small></button></nav></div>`;
function header(){return `<a class="skip-link" href="#conteudo">Ir para o conteúdo</a>
<header class="site-header"><a href="/pt/" class="brand" aria-label="DGX International Travel — início">${image(assets.logo,'DGX International Travel','',true)}</a>
<nav id="site-navigation" class="site-navigation" aria-label="Navegação principal"><a href="/pt/#dgx">A DGX</a><a href="/pt/#servicos">Serviços</a><a href="/pt/#mercados">Brasil ↔ México</a><a href="/pt/#portfolio">Portfólio</a><a href="/pt/#cases">Cases</a><a href="/pt/#contato">Contato</a></nav>
<div class="header-tools">${locale()}<button class="menu-toggle" aria-controls="site-navigation" aria-expanded="false" hidden>Menu <span class="menu-glyph" aria-hidden="true"></span></button></div></header>`;}
const footer=()=>`<footer class="site-footer"><div>${image(assets.logo,'DGX International Travel','footer-logo')}<p>Representação, estratégia e conexões.</p></div><div><p>São Paulo · Cidade do México</p><a href="mailto:info@dgxtravel.com">info@dgxtravel.com</a></div><div><a href="/?choose=1">Escolher idioma</a><p>© 2026 DGX International Travel</p></div></footer>`;
function doc(title,content,{entry=false,bodyClass=''}={}){return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#1e3c6e"><title>${title} · DGX International Travel</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/site.css"><link rel="stylesheet" href="/assets/css/refinement.css"><script src="/assets/js/site.js" defer></script></head><body class="${entry?'entry-page':bodyClass}">${entry?'':header()}${content}${entry?'':footer()}</body></html>`;}
const video=()=>`<video class="background-video" autoplay muted loop playsinline preload="metadata" poster="${imageRoot+assets.poster}" aria-hidden="true"><source src="${assets.video}" type="video/mp4"></video>`;
const videoControl=()=>'';
const entry=doc('Escolha seu idioma',`<main class="language-entry" id="conteudo">${video()}<div class="entry-shade"></div><div class="entry-identity">${image(assets.logo,'DGX International Travel','entry-logo',true)}<span class="entry-rule" aria-hidden="true"></span><nav class="entry-languages" aria-label="Selecione o idioma"><a href="/pt/" data-language="pt" lang="pt-BR">Português</a><span aria-hidden="true">·</span><button type="button" disabled lang="es" aria-describedby="future-languages">Español</button><span aria-hidden="true">·</span><button type="button" disabled lang="en" aria-describedby="future-languages">English</button></nav><p id="future-languages" class="language-note">Español e English em breve</p></div><p class="entry-location">Brasil <span aria-hidden="true">↔</span> México</p>${videoControl()}</main>`,{entry:true});

const services=[
 ['Representação<br>Comercial','Atuação como extensão local de destinos e empresas de turismo, desenvolvendo relacionamento comercial e oportunidades junto a operadoras, agências e parceiros estratégicos.'],
 ['Marketing &<br>Estratégia de Marca','Planejamento B2B e B2C, posicionamento, campanhas, comunicação e ações orientadas a awareness e conversão.'],
 ['Relações Públicas<br>& Imprensa','Relacionamento com mídia, press trips, pautas estratégicas, gestão de reputação e presença em veículos especializados.'],
 ['Eventos &<br>Ativações','Roadshows, eventos B2B/B2C, fam trips, feiras, experiências proprietárias e ativações especiais.'],
 ['Capacitação<br>do Trade','Treinamentos presenciais e digitais para operadoras, agentes de viagens e parceiros comerciais.'],
 ['Database &<br>Comunicação B2B','Comunicação e relacionamento direto com uma base de mais de 6.000 agências brasileiras.']
];
const methods=[['Imersão','Entendemos marca, posicionamento, desafios e oportunidades.'],['Estratégia','Definimos objetivos, canais, ações e indicadores.'],['Execução','Transformamos estratégia em trabalho comercial, capacitações, PR, eventos e campanhas.'],['Resultados','Acompanhamento, reporting, indicadores e inteligência de mercado.']];
const placeholder=(title,cls='')=>`<figure class="image-placeholder ${cls}"><span class="placeholder-orbit" aria-hidden="true"></span><figcaption><strong>${title}</strong><span>Seleção de imagens em breve</span></figcaption></figure>`;
const cases=[
 {name:'Los Cabos<br><em>Essência & Conexão</em>',meta:'2026 · Brasil',type:'Roadshow',copy:'Uma experiência proprietária para aproximar Los Cabos do trade, combinando apresentação do destino, relacionamento e oportunidades comerciais.',tags:['Representação','Eventos','Relacionamento com o trade'],photos:[['681afd544c42672d.jpg','Registro do roadshow Los Cabos'],['683eb9d0c2c426ba.jpg','Participantes do roadshow Los Cabos'],['1db79337a9e777e5.jpg','Encontro Los Cabos Essência & Conexão']]},
 {name:'SECTUR<br><em>México</em>',meta:'Ano e local em atualização',type:'Evento institucional',copy:'Um projeto para apresentar a atuação da DGX em encontros institucionais e conexões com o turismo mexicano.',tags:['Eventos','Relacionamento institucional'],placeholder:'SECTUR México'},
 {name:'Xcaret<br><em>Festuris 2025</em>',meta:'2025 · Local em atualização',type:'Trade & relacionamento',copy:'A presença de Xcaret em um encontro com o mercado de turismo. Uma conexão entre a identidade da marca e seus parceiros comerciais.',tags:['Representação','Trade','Eventos'],placeholder:'Xcaret · Festuris'},
 {name:'Los Cabos<br><em>MICE & Wedding</em>',meta:'2025 · Local em atualização',type:'Evento de segmento',copy:'Uma aproximação de Los Cabos com os universos de reuniões, incentivos e celebrações, criando espaço para novas conversas com o mercado.',tags:['Eventos','Representação','Relacionamento B2B'],placeholder:'Los Cabos · MICE & Wedding'},
 {name:'Tianguis<br><em>Turístico</em>',meta:'2026 · México',type:'Feira & trade',copy:'Presença internacional e relacionamento com o trade em um dos grandes encontros do turismo mexicano.',tags:['Representação','Trade','Eventos'],photos:[['7caf6f10c2b5dff2.jpg','Participação no Tianguis Turístico'],['ff750034fdf7430c.jpg','Los Cabos no Tianguis Turístico']]}
];
function caseMarkup(c,i){return `<article class="case" id="case-${i+1}"><div class="case-copy">${kicker(`${String(i+1).padStart(2,'0')} / ${c.type}`)}<p class="case-meta">${c.meta}</p><h3>${c.name}</h3><p>${c.copy}</p><p class="tag-label">Serviços DGX envolvidos</p><ul class="tags">${c.tags.map(t=>`<li>${t}</li>`).join('')}</ul></div><div class="case-visual">${c.photos?`<div class="case-gallery">${c.photos.map(([p,a],j)=>`<figure${j===0?' class="gallery-main"':''}>${image(p,a)}</figure>`).join('')}</div>`:`<div class="case-gallery pending-gallery">${placeholder(c.placeholder,'gallery-main')}${placeholder('Encontros')}${placeholder('Conexões')}</div>`}</div></article>`;}
const people=[['24de53f7dfa7d48c.png','Diana Pomar','Diretora Executiva · Co-founder'],['ae52a6d9fa6e820a.png','Gabriel Lopes','Diretor Executivo · Co-founder'],['9ec2573d51b1e854.png','Raquel Ramirez','Executiva Comercial'],['9fc79efde0b420fc.jpg','Gabriel Seles','Marketing Comercial'],['bee9717faccc9c90.png','Mario Araujo','Imprensa e Comunicação']];
const contact=`<section class="section contact" id="contato"><div class="contact-heading">${kicker('08 / Vamos conversar')}<h2>A próxima<br><strong>conexão.</strong></h2><p>Conte-nos sobre sua marca, seu destino ou o projeto que deseja construir.</p><a class="contact-email" href="mailto:info@dgxtravel.com">info@dgxtravel.com</a><p class="contact-locations">São Paulo<br>Cidade do México</p></div><form id="contact-form" class="contact-form"><p class="form-note" id="form-note">Prepare sua mensagem aqui e conclua o envio no seu aplicativo de e-mail. Os campos com * são obrigatórios.</p><div class="form-grid"><label>Nome *<input name="nome" autocomplete="name" required maxlength="120"></label><label>Empresa *<input name="empresa" autocomplete="organization" required maxlength="160"></label><label>Cargo<input name="cargo" autocomplete="organization-title" maxlength="120"></label><label>E-mail *<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>WhatsApp<input name="whatsapp" type="tel" autocomplete="tel" maxlength="40"></label><label>País<select name="pais"><option value="">Selecione</option><option>Brasil</option><option>México</option><option>Outro</option></select></label><label class="full">Área de interesse *<select name="interesse" required><option value="">Selecione</option>${['Representação','Marketing','PR & Imprensa','Eventos','Trade & Capacitações','Parcerias','Outro'].map(v=>`<option>${v}</option>`).join('')}</select></label><label class="full">Mensagem *<textarea name="mensagem" rows="4" required maxlength="3000"></textarea></label></div><label class="consent"><input type="checkbox" name="consentimento" required><span>Autorizo o tratamento dos dados informados pela DGX para responder a esta solicitação. *</span></label><button class="solid-link" type="submit" disabled aria-describedby="form-note">Preparar mensagem ${arrow}</button><div id="contact-result" class="contact-result" role="status" hidden><p>Sua mensagem está pronta. Abra seu aplicativo de e-mail para concluir o envio.</p><a id="email-draft" class="text-link">Abrir e-mail ${arrow}</a></div><noscript><p>Envie sua mensagem diretamente para <a href="mailto:info@dgxtravel.com">info@dgxtravel.com</a>.</p></noscript></form></section>`;
const home=doc('Representação, marketing e conexões',`<main id="conteudo"><section class="hero home-hero">${video()}<div class="hero-shade"></div><div class="hero-content">${kicker('Representação · Marketing · Turismo internacional')}<h1>O mundo<br><em>é feito de</em><br><strong>conexões.</strong></h1><p>Estratégia, presença comercial e relações que aproximam marcas, destinos e mercados.</p>${link('#servicos','Conheça nossa atuação','hero-link')}</div><div class="hero-bottom"><span>São Paulo ↔ Cidade do México</span><a href="#dgx">Explore ${arrow}</a></div>${videoControl()}</section>
<section class="section intro" id="dgx"><div>${kicker('01 / A DGX')}<h2>Sua marca.<br><strong>Nossa presença.</strong></h2></div><div class="intro-copy"><p class="lead">Somos uma extensão da sua marca no mercado.</p><p>Integramos vendas, marketing, relações públicas e eventos para transformar posicionamento em presença comercial. Construímos relações com operadoras, agências e parceiros do trade, conectando destinos e empresas de turismo às oportunidades de cada mercado.</p><p>Inteligência local, relacionamento próximo e execução estratégica. Do primeiro contato ao acompanhamento de resultados.</p></div></section>
<section class="section services" id="servicos"><div class="section-heading"><div>${kicker('02 / Serviços')}<h2>Estratégia que<br>se torna <strong>presença.</strong></h2></div><p>Seis frentes que trabalham juntas.<br>Uma atuação desenhada para cada marca.</p></div><div class="service-list">${services.map(([name,copy],i)=>`<article class="service-row"><h3><button class="service-trigger" type="button" aria-expanded="true" aria-controls="service-copy-${i}"><span class="index-number">0${i+1}</span><span>${name.replaceAll('<br>',' ')}</span><span class="service-symbol" aria-hidden="true"></span></button></h3><p id="service-copy-${i}">${copy}</p></article>`).join('')}</div></section>
<section class="section methodology" id="metodologia"><div class="section-heading"><div>${kicker('03 / Como trabalhamos')}<h2>Da imersão<br>ao <strong>resultado.</strong></h2></div><p>Visão de negócio em cada etapa.<br>Proximidade durante todo o caminho.</p></div><ol class="method-steps">${methods.map(([title,text],i)=>`<li><h3><button class="method-trigger" type="button" aria-expanded="true" aria-controls="method-copy-${i}"><span class="index-number">0${i+1}</span>${title}</button></h3><p id="method-copy-${i}">${text}</p></li>`).join('')}</ol></section>
<section class="section markets" id="mercados">${kicker('04 / Uma operação. Dois mercados.')}<div class="market-title"><h2>Brasil <span aria-hidden="true">↔</span> <strong>México</strong></h2><p>Conectamos marcas, destinos e parceiros aos mercados brasileiro e mexicano por meio de inteligência local, relacionamento comercial e execução estratégica.</p></div><figure class="geographic-map"><img src="/assets/images/americas.svg" alt="Mapa das Américas com conexão entre Cidade do México e São Paulo" loading="lazy" width="640" height="650"><figcaption>Uma operação. Dois mercados. A mesma presença estratégica.</figcaption></figure><div class="market-columns">${[['Brasil','Presença local. Conexões que abrem caminhos.'],['México','A mesma atuação estratégica em um novo mercado.']].map(([name,copy])=>`<article><h3>${name}</h3><p>${copy}</p><ul><li>Representação</li><li>Marketing</li><li>PR</li><li>Trade</li><li>Eventos</li><li>Capacitações</li></ul></article>`).join('')}</div></section>
<section class="portfolio" id="portfolio"><div class="section section-heading"><div>${kicker('05 / Portfólio')}<h2>Do extraordinário<br>ao <strong>inesquecível.</strong></h2></div><p>Destinos e marcas com identidade própria.<br>Conectados ao mercado pela DGX.</p></div><article class="product"><a class="product-image" href="/pt/portfolio/los-cabos/" aria-label="Conheça Los Cabos">${image(assets.cabos,'Paisagem e mar de Los Cabos')}</a><div class="product-copy">${kicker('01 / Destino')}<h3>Los <strong>Cabos</strong></h3><p>Entre o deserto e o mar, um destino que reúne hospitalidade, gastronomia e experiências extraordinárias.</p>${link('/pt/portfolio/los-cabos/','Conheça Los Cabos')}</div></article><article class="product product-xcaret"><a class="product-image" href="/pt/portfolio/xcaret/" aria-label="Conheça Xcaret">${image(assets.xcaret,'Hoteles Xcaret, México')}</a><div class="product-copy">${kicker('02 / Hospitalidade')}<h3>Hoteles<br><strong>Xcaret</strong></h3><p>Natureza, cultura mexicana e hospitalidade em um universo de experiências conectado pela DGX ao Brasil.</p>${link('/pt/portfolio/xcaret/','Conheça Xcaret')}</div></article></section>
<section class="section cases" id="cases"><div class="section-heading"><div>${kicker('06 / Cases & projetos em destaque')}<h2>Onde a estratégia<br><strong>ganha vida.</strong></h2></div><p>Projetos que aproximam marcas e pessoas.<br>Presença, relacionamento e capacidade de execução.</p></div>${cases.map(caseMarkup).join('')}</section>
<section class="section team" id="equipe"><div class="section-heading"><div>${kicker('07 / Pessoas')}<h2>Por trás de<br><strong>cada conexão.</strong></h2></div><p>Uma equipe próxima, estratégica e humana.<br>Conhecimento de mercado com presença real.</p></div><div class="people">${people.map(([photo,name,role])=>`<article class="person">${image(photo,name)}<h3>${name}</h3><p>${role}</p></article>`).join('')}</div></section>${contact}</main>`);

function destinationHero(name,subtitle,photo,alt){return `<section class="hero destination-hero">${image(photo,alt,'hero-image',true)}<div class="hero-shade"></div><div class="hero-content"><p class="breadcrumb"><a href="/pt/">DGX</a><span aria-hidden="true"> / </span><a href="/pt/#portfolio">Portfólio</a></p><h1>${name}</h1><p>${subtitle}</p><a class="hero-link" href="#visao">Explore o destino ${arrow}</a></div><div class="hero-bottom"><span>México · Portfólio DGX</span></div></section>`;}
const chapterNav=(items)=>`<nav class="chapter-nav" aria-label="Nesta página">${items.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}</nav>`;
const experienceSection=(id,num,title,copy)=>`<article class="experience-row" id="${id}"><div class="experience-copy"><span class="index-number">${num}</span><h3>${title}</h3><p>${copy}</p></div>${placeholder(title,'story-image')}</article>`;
const representation=(name,text,otherUrl,otherName)=>`<section class="section representation" id="representacao"><div>${kicker('Presença DGX')}<h2>${name}<br><strong>mais perto.</strong></h2></div><div><p class="lead">${text}</p><p>Representação comercial, relacionamento com o trade, capacitações, marketing, PR e encontros que transformam conhecimento em conexão.</p>${link('/pt/#contato','Converse com a DGX')}<div class="next-destination">${link(otherUrl,'Explore também '+otherName)}</div></div></section>`;
const cabos=doc('Los Cabos',`<main id="conteudo">${destinationHero('Los <strong>Cabos.</strong>','O encontro entre o deserto, o mar e o extraordinário.',assets.cabos,'Formações rochosas e mar em Los Cabos')}${chapterNav([['visao','O destino'],['experiencias','Experiências'],['conectividade','Conectividade'],['galeria','Galeria'],['representacao','DGX & Los Cabos']])}
<section class="section intro" id="visao"><div>${kicker('Baja California Sur · México')}<h2>Uma paisagem.<br><strong>Muitos universos.</strong></h2></div><div><p class="lead">Los Cabos combina a força do deserto com a imensidão do mar.</p><p>Um destino para descobrir por meio da hospitalidade, da gastronomia, do bem-estar e dos encontros. Uma identidade que convida a viver o México por outra perspectiva.</p></div></section>
<figure class="destination-panorama">${image(assets.cabos,'O encontro do mar com as formações rochosas de Los Cabos')}<figcaption>Los Cabos · Entre o deserto e o mar</figcaption></figure><section class="section destination-intro"><div>${kicker('Por que Los Cabos')}<h2>O luxo de<br><strong>sentir o lugar.</strong></h2></div><div class="destination-reasons"><p><span>01</span> Paisagens que definem a experiência.</p><p><span>02</span> Hospitalidade com personalidade.</p><p><span>03</span> Possibilidades para lazer, negócios e celebrações.</p></div></section>
<section class="section experience-list" id="experiencias"><div class="section-heading"><div>${kicker('Experiências')}<h2>Seu próximo<br><strong>capítulo.</strong></h2></div><p>Diferentes formas de conhecer um mesmo destino.</p></div>${[
 ['luxo','01','Luxo','Hospitalidade, arquitetura e atenção aos detalhes dão forma a uma experiência de viagem com identidade própria.'],
 ['gastronomia','02','Gastronomia','Uma viagem também se constrói à mesa. Ingredientes, paisagens e encontros inspiram a descoberta do destino.'],
 ['mice','03','MICE','Reuniões, incentivos e encontros corporativos encontram uma nova perspectiva em um cenário que aproxima pessoas.'],
 ['weddings','04','Weddings','Celebrações que fazem da paisagem parte da história. Uma proposta para conectar casais, profissionais e experiências.'],
 ['wellness','05','Wellness','Tempo para desacelerar, reconectar-se e descobrir o destino em outro ritmo.'],
 ['lgbtqia','06','LGBTQIA+','Uma abordagem de viagem que valoriza diversidade, acolhimento e experiências alinhadas a cada pessoa.']
 ].map(a=>experienceSection(...a)).join('')}</section>
<section class="section connectivity" id="conectividade"><div>${kicker('Conectividade')}<h2>O caminho<br><strong>também conecta.</strong></h2></div><div><p class="lead">Planejar a chegada é parte da experiência.</p><p>A DGX aproxima o trade das informações e dos parceiros do destino. Consulte nossa equipe para orientar sua pesquisa sobre acesso, conexões e oportunidades comerciais.</p>${link('/pt/#contato','Fale com nossa equipe')}</div></section>
<section class="section editorial-gallery" id="galeria"><div class="section-heading"><div>${kicker('Galeria editorial')}<h2>Entre o deserto<br><strong>e o mar.</strong></h2></div></div><div class="destination-gallery"><figure class="wide">${image(assets.cabos,'O mar e as formações rochosas de Los Cabos')}<figcaption>Los Cabos · México</figcaption></figure>${placeholder('Hospitalidade & arquitetura')}${placeholder('Gastronomia & encontros')}</div></section>
${representation('Los Cabos','A DGX aproxima Los Cabos do mercado brasileiro, conectando a identidade do destino a parceiros, profissionais e oportunidades.','/pt/portfolio/xcaret/','Xcaret')}</main>`,{bodyClass:'destination cabos'});
const xcaret=doc('Hoteles Xcaret',`<main id="conteudo">${destinationHero('Hoteles<br><strong>Xcaret.</strong>','México em sua forma mais viva.',assets.xcaret,'Vista dos Hoteles Xcaret e da natureza ao redor')}${chapterNav([['visao','Hoteles Xcaret'],['all-fun','All-Fun Inclusive'],['universo','Experiências'],['hoteis','Os hotéis'],['galeria','Galeria'],['representacao','DGX & Xcaret']])}
<section class="section intro" id="visao"><div>${kicker('Riviera Maya · México')}<h2>Hospitalidade.<br>Cultura.<br><strong>Natureza.</strong></h2></div><div><p class="lead">Um universo de experiências com a identidade do México.</p><p>Hoteles Xcaret reúne hospitalidade, paisagem e cultura mexicana em uma proposta que amplia a experiência de viajar. Diferentes hotéis, uma mesma conexão com o lugar.</p></div></section>
<figure class="destination-panorama">${image(assets.xcaret,'Arquitetura e paisagem dos Hoteles Xcaret')}<figcaption>Hoteles Xcaret · Riviera Maya</figcaption></figure><section class="section all-fun" id="all-fun">${kicker('O conceito')}<h2>All-Fun<br><strong>Inclusive.</strong></h2><div><p class="lead">A experiência vai além do hotel.</p><p>O conceito conecta a hospedagem aos parques e experiências do Grupo Xcaret, incluindo acesso e transporte a parques, conforme as condições de cada produto.</p>${link('#universo','Descubra esse universo')}</div></section>
<section class="section experience-list" id="universo"><div class="section-heading"><div>${kicker('O universo Xcaret')}<h2>O México<br><strong>em cada detalhe.</strong></h2></div></div>${[
 ['gastronomia','01','Gastronomia','Sabores, encontros e diferentes propostas à mesa fazem parte da experiência de hospitalidade.'],
 ['natureza','02','Natureza','A paisagem da Riviera Maya faz parte da atmosfera dos hotéis e convida à descoberta.'],
 ['cultura','03','Cultura mexicana','Identidade, expressão artística e tradições do México inspiram esse universo de experiências.'],
 ['parques','04','Parques & experiências','Uma conexão entre hospedagem e descobertas, com atividades que exploram natureza, cultura e aventura.']
 ].map(a=>experienceSection(...a)).join('')}</section>
<section class="section hotel-collection" id="hoteis"><div class="section-heading"><div>${kicker('Hoteles Xcaret')}<h2>Três nomes.<br><strong>Muitas descobertas.</strong></h2></div></div>${[
 ['Hotel Xcaret México','Uma porta de entrada para o universo Xcaret, conectando hospitalidade, paisagem e experiências.'],
 ['Hotel Xcaret Arte','Uma proposta de hospitalidade que coloca a expressão artística e a cultura mexicana no centro da experiência.'],
 ['La Casa de la Playa','Uma interpretação intimista da hospitalidade, conectada à paisagem e à identidade do México.']
 ].map(([name,copy],i)=>`<article class="hotel-row"><div>${kicker('0'+(i+1)+' / Coleção')}<h3>${name}</h3><p>${copy}</p></div>${placeholder(name)}</article>`).join('')}</section>
<section class="section editorial-gallery" id="galeria"><div class="section-heading"><div>${kicker('Galeria editorial')}<h2>Uma experiência<br><strong>que se sente.</strong></h2></div></div><div class="destination-gallery"><figure class="wide">${image(assets.xcaret,'Paisagem dos Hoteles Xcaret')}<figcaption>Hoteles Xcaret · México</figcaption></figure>${placeholder('Sabores do México')}${placeholder('Cultura & natureza')}</div></section>
${representation('Xcaret no Brasil','A DGX conecta Xcaret ao mercado brasileiro, aproximando sua proposta de hospitalidade de operadoras, agências e parceiros estratégicos.','/pt/portfolio/los-cabos/','Los Cabos')}</main>`,{bodyClass:'destination xcaret'});
write('index.html',entry);write('pt/index.html',home);write('pt/portfolio/los-cabos/index.html',cabos);write('pt/portfolio/xcaret/index.html',xcaret);
console.log('Generated language entry, Portuguese Home, Los Cabos and Xcaret.');
