const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.DGX_TEST_MODULES ? path.join(process.env.DGX_TEST_MODULES, 'playwright') : 'playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.DGX_REPORT_DIR || path.join(root,'work','review'));fs.mkdirSync(out,{recursive:true});
const base=process.env.DGX_TEST_URL||'http://127.0.0.1:4173';
const pages=['/?choose=1','/pt/','/pt/portfolio/los-cabos/','/pt/portfolio/xcaret/'];
const sizes=[{name:'desktop',width:1920,height:1080},{name:'notebook',width:1366,height:768},{name:'tablet',width:768,height:1024},{name:'mobile',width:390,height:844}];
function checkFiles(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.name==='.git'?[]:e.isDirectory()?checkFiles(path.join(dir,e.name)):[path.join(dir,e.name)])}
const files=checkFiles(root);assert(files.every(f=>fs.statSync(f).size<25*1024*1024));
for(const url of pages){const file=path.join(root,url.split('?')[0],'index.html');const html=fs.readFileSync(file,'utf8');assert(!html.includes(';base64,'));assert.equal((html.match(/<h1[ >]/g)||[]).length,url.startsWith('/?')?0:1);for(const match of html.matchAll(/(?:src|href|poster)="(\/[^"?#]*)(?:[?#][^"]*)?"/g)){let target=path.join(root,match[1]);if(match[1].endsWith('/'))target=path.join(target,'index.html');assert(fs.existsSync(target),'Missing '+match[1]);}}
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.DGX_TEST_BROWSER ? {executablePath:process.env.DGX_TEST_BROWSER} : {})});const results=[];try{for(const size of sizes){const context=await browser.newContext({viewport:{width:size.width,height:size.height}});await context.route('https://fonts.**/*',r=>r.abort());for(const route of pages){const page=await context.newPage();const errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)missing.push(r.url())});await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.evaluate(async()=>{document.querySelectorAll('img').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode()));document.querySelectorAll('video').forEach(v=>v.pause());await document.fonts.ready});await page.waitForTimeout(100);
const metrics=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),sections:[...document.querySelectorAll('main>section[id]')].map(x=>x.id),h1:document.querySelector('h1')?.getBoundingClientRect().toJSON(),hero:document.querySelector('.hero')?.getBoundingClientRect().toJSON(),videoFit:document.querySelector('video')?getComputedStyle(document.querySelector('video')).objectFit:null}));assert(metrics.scroll<=metrics.viewport,`Overflow ${size.name} ${route}: ${metrics.scroll}`);assert.deepEqual(metrics.broken,[]);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);if(metrics.videoFit)assert.equal(metrics.videoFit,'cover');if(metrics.h1)assert(metrics.h1.y>=78&&metrics.h1.bottom<=metrics.hero.bottom,`Hero title clipped: ${size.name} ${route}`);
const name=route==='/pt/'?'home':route.includes('los-cabos')?'los-cabos':route.includes('xcaret')?'xcaret':'entry';await page.screenshot({path:path.join(out,`${name}-${size.name}.png`),fullPage:true});
if(name!=='entry'){assert.equal(await page.locator('.locales button:disabled').count(),2);if(size.width<=1024){await page.click('.menu-toggle');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');assert(await page.locator('#site-navigation').isVisible());await page.screenshot({path:path.join(out,`menu-${name}-${size.name}.png`)});await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');assert(!await page.locator('#site-navigation').isVisible());await page.click('.menu-toggle');await page.click('#site-navigation a[href="/pt/#contato"]');await page.waitForURL('**/pt/#contato');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');}}
results.push({page:name,viewport:size.name,width:size.width,height:size.height,overflow:false,missingAssets:missing,errors,sections:metrics.sections});await page.close()}await context.close()}
const context=await browser.newContext({viewport:{width:1366,height:768}});await context.route('https://fonts.**/*',r=>r.abort());const page=await context.newPage();await page.goto(base+'/?choose=1');await page.click('[data-language="pt"]');await page.waitForURL('**/pt/');assert.equal(await page.evaluate(()=>localStorage.getItem('dgx-language')),'pt');await page.goto(base+'/');await page.waitForURL('**/pt/');await page.click('.locales a');await page.waitForURL('**/?choose=1');assert(await page.locator('.language-entry').isVisible());results.push({languageEntry:'passed',rememberedPreference:'passed',returnToEntry:'passed'});
await page.goto(base+'/pt/#contato');assert.equal(await page.locator('#contact-result').isVisible(),false);await page.click('button[type=submit]');assert.equal(await page.locator('#contact-result').isVisible(),false);await page.fill('[name=nome]','Revisão DGX');await page.fill('[name=empresa]','Empresa de teste');await page.fill('[name=email]','teste@example.com');await page.selectOption('[name=interesse]','Marketing');await page.fill('[name=mensagem]','Teste de estrutura. Nenhum e-mail será enviado.');await page.check('[name=consentimento]');await page.click('button[type=submit]');assert(await page.locator('#contact-result').isVisible());const draft=await page.locator('#email-draft').getAttribute('href');assert(draft.startsWith('mailto:info@dgxtravel.com?'));assert(decodeURIComponent(draft).includes('Revisão DGX'));await page.fill('[name=nome]','Revisão atualizada');assert.equal(await page.locator('#contact-result').isVisible(),false);results.push({formValidation:'passed',consentRequired:true,emailDraft:'passed',noMessageSent:true});await context.close();
const reduced=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}});await reduced.route('https://fonts.**/*',r=>r.abort());const p=await reduced.newPage();await p.goto(base+'/?choose=1');assert(await p.locator('video').evaluate(v=>v.paused));assert.equal(await p.locator('.video-control').isVisible(),false);await p.screenshot({path:path.join(out,'entry-reduced-motion.png')});await reduced.close();results.push({reducedMotion:'passed'});
fs.writeFileSync(path.join(out,'tests.json'),JSON.stringify({externalFonts:'Blocked in controlled local test; production stylesheet retained',maxFileBytes:Math.max(...files.map(f=>fs.statSync(f).size)),results},null,2));console.log(JSON.stringify(results));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
